# Default Settings
defaults:
  max_keywords: 100
  crawl_depth: 50
  approval_required: true

# Output Preferences (for CLI)
output:
  reports_folder: "./data/exports"

# AI Settings
ai:
  model: "gpt-4-turbo-preview"
  max_tokens: 2000
  temperature: 0.3

# API Keys (will be overridden by environment variables if present)
apis:
  openai_key: ""
  serpapi_key: ""
  ahrefs_key: ""
  semrush_key: ""
