[tool.ruff]
target-version = "py311"
line-length = 88
indent-width = 4
# Enable Pyflakes, pycodestyle, isort, and more
select = ["E", "F", "I", "W", "D", "N", "C90", "B", "UP", "PL", "RUF"]
ignore = ["D203", "D212"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.ruff.isort]
known-first-party = ["seo_agent"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_defs = false
disallow_incomplete_defs = false
