name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Install dependencies
      run: |
        poetry install --with dev
    - name: Lint with Ruff
      run: |
        poetry run ruff check seo_agent cli.py api.py utils.py
    - name: Format check with Ruff
      run: |
        poetry run ruff format --check seo_agent cli.py api.py utils.py
    - name: Type check with mypy
      run: |
        poetry run mypy seo_agent cli.py api.py utils.py
